name: 📦 Size Limit

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  size:
    permissions:
      checks: read
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: size-limit
        uses: ant-design/size-limit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          PRODUCTION_ONLY: 1
          NO_DUP_CHECK: 1
